### PR TITLE
Incremental update

### LINKED ISSUE #162: Incremental update
This change will introduce support for the [create](https://hl7.org/fhir/r4/http.html#create) and [update](https://hl7.org/fhir/r4/http.html#update) operations on all resources, and also the [transaction](https://hl7.org/fhir/r4/http.html#transaction) operation. The intent is that the updates will be made available within aggregate and search queries (close to) immediately.

Implementation considerations:

- Will updates be persisted to the Parquet files immediately?
- Will a large number of individual updates change the query performance characteristics of the datasets involved?
- Will each creation or update operation be expensive? Will it need to be queued somehow?
- Will historical versions be persisted?

See also: [Incremental update](https://pathling.csiro.au/docs/roadmap.html#incremental-update)

### PR DESCRIPTION
**Pull request by johngrimes**
Resolves #162.

### CODE REVIEW

**Comment by johngrimes** [comment]
@yeexianfong Looks like the tests did pass after all…

**Comment by yeexianfong** [comment]
@johngrimes that's awesome. Looks like we are off to a great start already.

**Comment by yeexianfong** [comment]
@johngrimes I have committed the latest changes I have been working on so far. It is safe for you to restructure my code from now onwards.

I will start working on streamlining the real-time FHIR project now. Will let you know in case I need to make any modifications on the pathling codebase.

**Comment by yeexianfong** [comment]
Also, I did not include the apache kafka dependencies in the pom.xml files.

**Pull request merged**
