### PR TITLE
Query optimisation and element identity

### LINKED ISSUE #142: Optimise boolean expression within where argument
The following expression is quite simple but performs exceptionally poorly. It also seems to use a very large amount of memory.

```
reverseResolve(Observation.subject)
    .where(
        $this.status = 'preliminary'
        or
        $this.status = 'final'
    ).status
```

### PR DESCRIPTION
**Pull request by piotrszul**
Fixes #142, #151 and #158.

### CODE REVIEW

**Comment by johngrimes** [comment]
@piotrszul The next task is to merge `issue/158` into this branch and get the tests passing.

**Comment by johngrimes** [comment]
@piotrszul Also, all `@Disabled` tests will need to be re-enabled and passing.

**Comment by johngrimes** [comment]
@piotrszul I'm ready to merge this when you are happy with the changes I've made.

**Comment by piotrszul** [comment]
@johngrimes   I have two suggestions:

in:

```
  @Nonnull
  public static Dataset<Row> join(@Nonnull final FhirPath left, @Nonnull final FhirPath right,
      @Nonnull final JoinType joinType) {
    final List<Column> leftColumns = new ArrayList<>();
    final List<Column> rightColumns = new ArrayList<>();
    leftColumns.add(left.getIdColumn());
    rightColumns.add(right.getIdColumn());

    // If the two paths are NonLiteralPaths, and they have $this columns, we need to add the element
    // ID columns into the join condition. This is to prevent too many rows being generated when
    // there are more rows than resources on either side of the join.
    final boolean nonLiteralJoin =
        left instanceof NonLiteralPath && right instanceof NonLiteralPath;
    if (nonLiteralJoin && ((NonLiteralPath) left).getThisColumn().isPresent()
        && ((NonLiteralPath) right).getThisColumn().isPresent()) {
      leftColumns.add(((NonLiteralPath) left).getThisColumn().get());
      rightColumns.add(((NonLiteralPath) right).getThisColumn().get());
    }

    return join(left.getDataset(), leftColumns, right.getDataset(), rightColumns, joinType);
  }
```

we do not actually need join on the entire $this column but only on the "eid" field of the structure (may possibly be more performant)

**Comment by piotrszul** [comment]
and in:

```
  @Nonnull
  private Dataset<Row> joinGroupingsAndFilters(@Nonnull final Collection<FhirPath> groupings,
      @Nonnull final Collection<FhirPath> filters, @Nonnull final Column idColumn) {
    final List<Dataset<Row>> datasets = groupings.stream()
        .map(grouping -> {
          // We need to remove any trailing null values from non-empty collections, so that
          // aggregations do not count non-empty collections in the empty collection grouping. We do
          // this by joining the distinct set of resource IDs to the dataset using an outer join,
          // where the value is not null.
          final Dataset<Row> distinctIds = grouping.getDataset().select(idColumn).distinct();
          return join(grouping.getDataset(), idColumn, distinctIds,
              idColumn, grouping.getValueColumn().isNotNull(), JoinType.RIGHT_OUTER);
        }).collect(Collectors.toList());
    datasets.addAll(filters.stream()
        .map(FhirPath::getDataset)
        .collect(Collectors.toList()));

    return datasets.stream()
        .reduce((a, b) -> join(a, idColumn, b, idColumn, JoinType.LEFT_OUTER))
        .orElseThrow();
  }
```

If the base resource is the same then perhaps  we could join all the filters and grouping with a normal join (filtering for null values) and at the very end do do left join to  distinct resource IDs.

**Comment by johngrimes** [comment]
@ametke I think we're ready for you to pick this up again (on the `v3` branch) and try it out with your data.

We still have a few tickets to close ahead of the official v3 release, but I think we're close enough to get your feedback.

**Pull request merged**
